--liquibase formatted sql
--changeSet abed:001-01
CREATE TABLE coins
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol    VARCHAR(100) NOT NULL,
    price_usd DECIMAL      NOT NULL
);

-- rollback DROP TABLE coins